const SET_USER = 'SET_USER'
const REMOVE_USER = 'REMOVE_USER'
const SET_CURRENT_USERS = 'SET_CURRENT_USERS'
const SET_CURRENT_NUMBER_PLAYERS = 'SET_CURRENT_NUMBER_PLAYERS'
const SET_CURRENT_PLAYER_ROLES = 'SET_CURRENT_PLAYER_ROLES'
const LOGIN_USER = 'LOGIN_USER'

export default {
  SET_USER,
  REMOVE_USER,
  SET_CURRENT_NUMBER_PLAYERS,
  SET_CURRENT_PLAYER_ROLES,
  LOGIN_USER,
  SET_CURRENT_USERS
}
