// initialization

// users
export const USERS_INIT = 'USER_INIT'
export const USERS_LOADING = 'GAMES_LOADING'
export const USERS_FAILED = 'GAMES_FAILED'

// notes
export const NOTES_INIT = 'NOTES_INIT'
export const NOTES_LOADING = 'GAMES_LOADING'
export const NOTES_FAILED = 'GAMES_FAILED'

// games
export const GAMES_INIT = 'GAMES_INIT'
export const GAMES_LOADING = 'GAMES_LOADING'
export const GAMES_FAILED = 'GAMES_FAILED'
export const NEW_GAME = 'NEW_GAME'

// roles
export const ROLES_INIT = 'ROLES_INIT'
export const ROLES_LOADING = 'ROLES_LOADING'
export const ROLES_FAILED = 'ROLES_FAILED'

// user authentication
export const REGISTER_USER = 'REGISTER_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const ADD_USER = 'ADD_USER'
export const NEW_USER = 'NEW_USER'

// notifications
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE'
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'

// session control
export const NEW_ROLE = 'NEW_ROLE'
export const USER_IS_NOT_LOGGED_IN = 'USER_IS_NOT_LOGGED_IN'
export const USER_IS_LOGGED_IN = 'USER_IS_LOGGED_IN'
export const SET_LOCAL_USER_STATE = 'SET_LOCAL_USER_STATE'
export const SET_CURRENT_USERS = 'SET_CURRENT_USERS'
export const SET_CURRENT_NUMBER_PLAYERS = 'SET_CURRENT_NUMBER_PLAYERS'
export const SET_CURRENT_PLAYER_ROLES = 'SET_CURRENT_PLAYER_ROLES'
export const CLEAR_CURRENT_PLAYER_ROLES = 'CLEAR_CURRENT_PLAYER_ROLES'
export const TOGGLE_CREATE_USER_FORM = 'TOGGLE_CREATE_USER_FORM'
export const TOGGLE_LOGIN_FORM = 'TOGGLE_LOGIN_FORM'
export const TOGGLE_NEW_NOTE_FORM = 'TOGGLE_NEW_NOTE_FORM'
export const DISTRIBUTE_ROLES = 'DISTRIBUTE_ROLES'
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE'
export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE'

// toggles
export const TOGGLE_LOGO = 'TOGGLE_LOGO'
